server:
  port: 9000
  servlet:
    context-path: /${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9001
logging:
  level:
    root: info
    org.springframework.security: trace
spring:
  application:
    name: auth-server
  webflux:
    base-path: ${server.servlet.context-path}
  security:
    user:
      name: edan
      password: pwd_edan
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "user"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types: "authorization_code"
              scopes:
                - "user.read"
                - "user.write"
              redirect-uris:
                - https://oauthdebugger.com/debug
            token:
              access-token-time-to-live: 3600s
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect